// Generated by scripts/generate-widget-renderer-contract.mjs. Do not edit.
// Edit src/widgets/widget-renderer-contract.json and regenerate instead.

package com.loofit.workoutcore

internal object LoofitWidgetLayoutContract {
  const val calendarColumns = 7
  const val contentPadding = 12f
  const val containerRadius = 24f

  object Heatmap {
    const val weekRangeDays = 7
    const val monthRangeWeeks = 5
    const val sixMonthRangeMonths = 6
    const val monthBoundaryGapSlots = 7
    const val currentMonthMaxRows = 6
    const val fourWeekExpandedRangeWeeks = 4
  }

  object RoutineProgress {
    const val visibleItemLimit = 3
  }

  object BodyPartDuration {
    const val rangeDays = 30
    const val visibleItemLimit = 4
  }

  object LockScreen {
    const val threeWeekCalendarRangeWeeks = 3
    const val nextThreeWeekCalendarRangeWeeks = 3
  }
}
