// Generated by scripts/generate-widget-renderer-contract.mjs. Do not edit.
// Edit src/widgets/widget-renderer-contract.json and regenerate instead.

import CoreGraphics
import SwiftUI
import WidgetKit

enum LoofitHeatmapHeaderSummary {
  case none
  case count
  case countTotalAverage
}

enum LoofitHeatmapCalendarAlignment {
  case rollingDays
  case calendarWeeks
  case continuousMonthsWithBoundarySlots
}

enum LoofitHeatmapStat {
  case count
  case totalDuration
  case averageDuration
}

enum LoofitHeatmapCellLabelColorRole {
  case detail
  case title
  case accentText
}

struct LoofitHeatmapRendererSpec {
  let title: String
  let rangeDays: Int
  let rangeWeeks: Int
  let rangeMonths: Int
  let columns: Int
  let contentPadding: CGFloat
  let cellGap: CGFloat
  let cellRadius: CGFloat
  let cellLabelSize: CGFloat
  let headerGap: CGFloat
  let headerVisible: Bool
  let headerFontSize: CGFloat
  let headerSummary: LoofitHeatmapHeaderSummary
  let calendarAlignment: LoofitHeatmapCalendarAlignment
  let showLeadingCalendarCells: Bool
  let monthBoundaryGapSlots: Int
  let reservedHeaderHeight: CGFloat
  let reservedFooterHeight: CGFloat
}

enum LoofitWidgetRendererContract {
  static let version = 1
  static let contentPadding: CGFloat = 16

  enum Control {
    static let headerHeight: CGFloat = 14
    static let bodyHeight: CGFloat = 54
    static let bodyGap: CGFloat = 4
    static let activeDotSize: CGFloat = 7
    static let activeDotGap: CGFloat = 6
    static let buttonHeight: CGFloat = 28
    static let buttonRadius: CGFloat = 12
    static let footerHeight: CGFloat = 41
    static let footerGap: CGFloat = 1
    static let titleSize: CGFloat = 19
    static let timerSize: CGFloat = 26
    static let detailSize: CGFloat = 13
    static let buttonTextSize: CGFloat = 13
    static let durationSize: CGFloat = 22
    static let rangeSize: CGFloat = 11
  }

  enum LiveActivity {
    enum Compact {
      static let leadingWidth: CGFloat = 48
      static let trailingWidth: CGFloat = 48
      static let fontSize: CGFloat = 11
    }

    enum Expanded {
      static let titleRegion: DynamicIslandExpandedRegionPosition = .leading
      static let timerRegion: DynamicIslandExpandedRegionPosition = .center
      static let endButtonRegion: DynamicIslandExpandedRegionPosition = .trailing
      static let sideRegionAlignment: Alignment = .center
      static let timerAlignment: Alignment = .trailing
      static let timerRegionPriority: Double = 1
      static let titleFontSize: CGFloat = 14
      static let titleMinimumScaleFactor: CGFloat = 0.76
      static let timerFontSize: CGFloat = 14
      static let timerLineHeight: CGFloat = 14
      static let buttonWidth: CGFloat = 60
      static let buttonHeight: CGFloat = 26
      static let buttonFontSize: CGFloat = 11
    }
  }

  enum Heatmap {
    static let weekdayLabels = ["일", "월", "화", "수", "목", "금", "토"]
    static let weekdayLabelSize: CGFloat = 8
    static let emptyCellLabelColorRole: LoofitHeatmapCellLabelColorRole = .detail
    static let filledCellLabelColorRole: LoofitHeatmapCellLabelColorRole = .title
    static let strongFilledCellLabelColorRole: LoofitHeatmapCellLabelColorRole = .accentText
    static let strongCellLabelMinimumDurationSeconds = 3600
    static let week = LoofitHeatmapRendererSpec(
      title: "지난 7일",
      rangeDays: 7,
      rangeWeeks: 0,
      rangeMonths: 0,
      columns: 7,
      contentPadding: 16,
      cellGap: 4,
      cellRadius: 4,
      cellLabelSize: 8,
      headerGap: 8,
      headerVisible: false,
      headerFontSize: 11,
      headerSummary: .none,
      calendarAlignment: .rollingDays,
      showLeadingCalendarCells: false,
      monthBoundaryGapSlots: 0,
      reservedHeaderHeight: 0,
      reservedFooterHeight: 63
    )
    static let month = LoofitHeatmapRendererSpec(
      title: "지난 5주",
      rangeDays: 0,
      rangeWeeks: 5,
      rangeMonths: 0,
      columns: 7,
      contentPadding: 12,
      cellGap: 3,
      cellRadius: 3,
      cellLabelSize: 7,
      headerGap: 8,
      headerVisible: false,
      headerFontSize: 11,
      headerSummary: .none,
      calendarAlignment: .calendarWeeks,
      showLeadingCalendarCells: false,
      monthBoundaryGapSlots: 0,
      reservedHeaderHeight: 0,
      reservedFooterHeight: 0
    )
    static let year = LoofitHeatmapRendererSpec(
      title: "지난 6개월",
      rangeDays: 0,
      rangeWeeks: 0,
      rangeMonths: 6,
      columns: 0,
      contentPadding: 16,
      cellGap: 2,
      cellRadius: 2,
      cellLabelSize: 0,
      headerGap: 8,
      headerVisible: true,
      headerFontSize: 10,
      headerSummary: .countTotalAverage,
      calendarAlignment: .continuousMonthsWithBoundarySlots,
      showLeadingCalendarCells: true,
      monthBoundaryGapSlots: 7,
      reservedHeaderHeight: 22,
      reservedFooterHeight: 0
    )

    static let monthLabelSize: CGFloat = 9
    static let monthLabelHeight: CGFloat = 12
    static let monthHeaderBottomGap: CGFloat = 12

    enum WeekFooter {
      static let statOrder: [LoofitHeatmapStat] = [.count, .totalDuration, .averageDuration]
      static let statLabels = ["횟수", "총 시간", "평균"]
      static let recentLabel = "최근 운동"
      static let emptyRecentLabel = "아직 기록 없음"
      static let alwaysShowRecent = true
      static let recentLimit = 2
      static let topRowGap: CGFloat = 8
      static let statGap: CGFloat = 4
      static let recentRowGap: CGFloat = 2
      static let statLabelSize: CGFloat = 8
      static let statValueSize: CGFloat = 14
      static let recentLabelSize: CGFloat = 8
      static let recentValueSize: CGFloat = 10
      static let recentMetaSize: CGFloat = 9
    }
  }

  enum LockScreen {
    static let active = "운동 중"
    static let completedEyebrow = "오늘 완료"
    static let completedBadge = "오운완"
    static let idle = "다음 운동"
    static let routineRequired = "루틴 설정 필요"
    static let summaryTitle = "지난 7일"
    static let compactCharacterLimit = 3
    static let summaryDays = 7
    static let inlineFontSize: CGFloat = 13
    static let circularDefaultFontSize: CGFloat = 18
    static let circularCompletedFontSize: CGFloat = 15
    static let rectangularTitleFontSize: CGFloat = 30
    static let rectangularDetailFontSize: CGFloat = 18

    enum Summary {
      static let cellSize: CGFloat = 18
      static let cellGap: CGFloat = 3
      static let cellRadius: CGFloat = 5
      static let fontSize: CGFloat = 15
      static let contentGap: CGFloat = 6
      static let contentPadding: CGFloat = 4
    }
  }
}
