// Generated by scripts/generate-widget-renderer-contract.mjs. Do not edit.
// Edit src/widgets/widget-renderer-contract.json and regenerate instead.

import CoreGraphics
import SwiftUI
import WidgetKit

enum LoofitHeatmapHeaderSummary {
  case none
  case count
  case countTotalAverage
}

enum LoofitHeatmapCalendarAlignment {
  case rollingDays
  case calendarWeeks
  case continuousMonthsWithBoundarySlots
}

enum LoofitHeatmapStat {
  case count
  case totalDuration
  case averageDuration
}

enum LoofitHeatmapCellLabelColorRole {
  case textLow
  case textHigh
  case onAccent
}

struct LoofitHeatmapRendererSpec {
  let title: String
  let rangeDays: Int
  let rangeWeeks: Int
  let rangeMonths: Int
  let columns: Int
  let contentPadding: CGFloat
  let cellGap: CGFloat
  let cellRadius: CGFloat
  let cellLabelSize: CGFloat
  let cellLabelMinimumScaleFactor: CGFloat
  let headerGap: CGFloat
  let headerVisible: Bool
  let headerFontSize: CGFloat
  let headerLineHeight: CGFloat
  let headerMinimumScaleFactor: CGFloat
  let headerSummary: LoofitHeatmapHeaderSummary
  let calendarAlignment: LoofitHeatmapCalendarAlignment
  let showLeadingCalendarCells: Bool
  let monthBoundaryGapSlots: Int
  let reservedHeaderHeight: CGFloat
  let reservedFooterHeight: CGFloat
}

enum LoofitWidgetRendererContract {
  static let version = 1
  static let fingerprint = "b0721ee28787205cb8a0ba6aeef2bfd47ab565fb16093822faab27eb138e96f4"
  static let contentPadding: CGFloat = 12

  enum ContentMargins {
    static let homeReferenceShortestEdge: CGFloat = 158
  }

  enum PreviewViewports {
    static let homeSmall = CGSize(width: 158, height: 158)
    static let homeMedium = CGSize(width: 338, height: 158)
    static let accessoryRectangular = CGSize(width: 160, height: 72)
  }

  enum PreviewData {
    static let paletteJSON = "{\"light\":{\"surface\":\"#F5F5F6\",\"raisedSurface\":\"#EDEDEF\",\"textHigh\":\"#17171A\",\"textMedium\":\"#3A3A40\",\"textLow\":\"#78787F\",\"textWeekend\":\"#C0392B\",\"accent\":\"#CFF56A\",\"onAccent\":\"#0B0B0B\",\"heatmapBase\":\"#FFFFFF\",\"heatmapEmpty\":\"#E7E7EB\",\"todayIndicator\":\"#000000\"},\"dark\":{\"surface\":\"#141416\",\"raisedSurface\":\"#1B1B1F\",\"textHigh\":\"#F4F4F2\",\"textMedium\":\"#C9C9CE\",\"textLow\":\"#7C7C82\",\"textWeekend\":\"#C87A7A\",\"accent\":\"#CFF56A\",\"onAccent\":\"#0B0B0B\",\"heatmapBase\":\"#16161A\",\"heatmapEmpty\":\"#1B1B1F\",\"todayIndicator\":\"#FFFFFF\"}}"
    static let fixtureJSON = "{\"control\":{\"idle\":{\"eyebrow\":\"다음 운동\",\"title\":\"Pull\",\"detail\":\"등 · 이두\",\"action\":\"운동 시작\"},\"active\":{\"eyebrow\":\"운동 중\",\"elapsed\":\"42:10\",\"detail\":\"등 · 이두\",\"action\":\"운동 종료\"},\"completed\":{\"eyebrow\":\"오늘 운동 완료\",\"title\":\"Push\",\"detail\":\"가슴 · 어깨 · 삼두\",\"duration\":\"1시간 8분\",\"range\":\"오후 7:24 – 오후 8:32\"}},\"routineProgress\":{\"currentIndex\":1,\"items\":[{\"split\":\"Push\",\"bodyParts\":\"가슴·어깨·삼두\",\"duration\":\"1시간 8분\",\"relativeDay\":\"어제\"},{\"split\":\"Pull\",\"bodyParts\":\"등·이두\",\"duration\":\"48분\",\"relativeDay\":\"오늘\"},{\"split\":\"\",\"bodyParts\":\"하체\",\"duration\":\"56분\",\"relativeDay\":\"4일 전\"},{\"split\":\"Upper\",\"bodyParts\":\"가슴·등\",\"duration\":\"42분\",\"relativeDay\":\"6일 전\"}]},\"bodyPartDuration\":[{\"bodyPart\":\"가슴\",\"durationSeconds\":23100},{\"bodyPart\":\"등\",\"durationSeconds\":20400},{\"bodyPart\":\"하체\",\"durationSeconds\":15300},{\"bodyPart\":\"어깨\",\"durationSeconds\":9000}],\"heatmap\":{\"anchorDate\":\"2026-07-18\",\"durationPatternSeconds\":[0,1200,2400,3600,5400,7200,3000,0,4200,6600]},\"notification\":{\"title\":\"하체 · 어깨\",\"detail\":\"운동 중\",\"elapsed\":\"42:10\",\"action\":\"운동 종료\"}}"
  }

  enum FontWeight {
    static let bold: Font.Weight = .heavy
    static let medium: Font.Weight = .bold
    static let light: Font.Weight = .semibold
  }

  enum Spacing {
    static let xs: CGFloat = 2
    static let sm: CGFloat = 4
    static let md: CGFloat = 8
    static let lg: CGFloat = 12
  }

  enum Radius {
    static let cell: CGFloat = 3
    static let control: CGFloat = 12
    static let container: CGFloat = 24
  }

  enum Opacity {
    static let defaultValue: Double = 1
    static let muted: Double = 0.72
  }

  enum MinimumScale {
    static let compact: CGFloat = 0.48
    static let calendar: CGFloat = 0.6
    static let display: CGFloat = 0.62
    static let dense: CGFloat = 0.68
    static let timer: CGFloat = 0.72
    static let defaultValue: CGFloat = 0.75
  }

  enum Control {
    static let bodyGap: CGFloat = 4
    static let activeDotSize: CGFloat = 7
    static let activeDotGap: CGFloat = 8
    static let buttonHeight: CGFloat = 28
    static let buttonRadius: CGFloat = 12
    static let footerGap: CGFloat = 2
    static let titleSize: CGFloat = 16
    static let titleMinimumScaleFactor: CGFloat = 0.75
    static let timerSize: CGFloat = 26
    static let timerMinimumScaleFactor: CGFloat = 0.72
    static let detailSize: CGFloat = 12
    static let buttonTextSize: CGFloat = 12
    static let durationSize: CGFloat = 26
    static let rangeSize: CGFloat = 12

    enum Copy {
      static let idle = "다음 운동"
      static let active = "운동 중"
      static let completed = "오늘 운동 완료"
      static let start = "운동 시작"
      static let end = "운동 종료"
      static let routineRequired = "루틴 설정 필요"
    }
  }

  enum CurrentMonth {
    static let contentPadding: CGFloat = 12
    static let cellGap: CGFloat = 4
    static let cellRadius: CGFloat = 3
    static let cellLabelSize: CGFloat = 8
    static let cellLabelMinimumScaleFactor: CGFloat = 0.6
    static let headerGap: CGFloat = 8
    static let headerFontSize: CGFloat = 12
    static let headerLineHeight: CGFloat = 16
    static let headerMinimumScaleFactor: CGFloat = 0.75
    static let headerOpacity: Double = 0.72
    static let denseRowThreshold = 6
    static let denseVerticalGap: CGFloat = 2
    static let denseHeaderGap: CGFloat = 4
    static let denseWeekdayHeaderHeight: CGFloat = 10
    static let outsideMonthDateLabelOnly = true
    static let todayIndicatorWidth: CGFloat = 1.5
  }

  enum FourWeekExpanded {
    static let rangeWeeks = 4
    static let columns = 7
    static let contentPadding: CGFloat = 12
    static let cellGap: CGFloat = 4
    static let cellRadius: CGFloat = 3
    static let cellLabelSize: CGFloat = 8
    static let cellLabelMinimumScaleFactor: CGFloat = 0.6
    static let cellLabelLineHeight: CGFloat = 10
    static let bodyPartLabelSize: CGFloat = 8
    static let bodyPartLabelLineHeight: CGFloat = 10
    static let bodyPartLabelOpacity: Double = 0.72
    static let cellContentGap: CGFloat = 2
    static let weekdayHeaderHeight: CGFloat = 10
    static let headerGap: CGFloat = 4
    static let bodyPartSeparator = "·"
  }

  enum RoutineProgress {
    static let visibleItemLimit = 4
    static let contentPadding: CGFloat = 12
    static let twoItemGap: CGFloat = 12
    static let compactItemCount = 4
    static let compactVerticalContentPadding: CGFloat = 8
    static let metadataSeparator = " · "
    static let emptyRelativeDay = "기록 없음"
    static let splitSize: CGFloat = 26
    static let splitWeight: Font.Weight = .heavy
    static let compactSplitSize: CGFloat = 16
    static let compactSplitWeight: Font.Weight = .heavy
    static let metadataSize: CGFloat = 8
    static let metadataWeight: Font.Weight = .bold

    enum LockScreen {
      static let visibleItemLimit = 3
      static let contentPadding: CGFloat = 4
      static let columnGap: CGFloat = 4
      static let itemGap: CGFloat = 2
      static let workoutSize: CGFloat = 16
      static let workoutWeight: Font.Weight = .heavy
      static let relativeDaySize: CGFloat = 12
      static let relativeDayWeight: Font.Weight = .bold
    }
  }

  enum BodyPartDuration {
    static let rangeDays = 30
    static let visibleItemLimit = 4
    static let title = "최근 30일"
    static let contentPadding: CGFloat = 12
    static let barHeight: CGFloat = 4
    static let barRadius: CGFloat = 3
    static let titleSize: CGFloat = 12
    static let titleWeight: Font.Weight = .heavy
    static let bodyPartSize: CGFloat = 12
    static let bodyPartWeight: Font.Weight = .heavy
    static let durationSize: CGFloat = 8
    static let durationWeight: Font.Weight = .bold
  }

  enum LiveActivity {
    enum Banner {
      static let contentPadding: CGFloat = 12
      static let contentGap: CGFloat = 8
      static let rowGap: CGFloat = 4
      static let titleFontSize: CGFloat = 16
      static let titleMinimumScaleFactor: CGFloat = 0.75
      static let statusFontSize: CGFloat = 12
      static let timerFontSize: CGFloat = 26
      static let buttonWidth: CGFloat = 88
      static let buttonHeight: CGFloat = 32
      static let buttonFontSize: CGFloat = 12
    }

    enum Compact {
      static let leadingWidth: CGFloat = 48
      static let trailingWidth: CGFloat = 48
      static let fontSize: CGFloat = 12
    }

    enum Minimal {
      static let fontSize: CGFloat = 12
      static let minimumScaleFactor: CGFloat = 0.72
    }

    enum Expanded {
      static let titleRegion: DynamicIslandExpandedRegionPosition = .leading
      static let timerRegion: DynamicIslandExpandedRegionPosition = .center
      static let endButtonRegion: DynamicIslandExpandedRegionPosition = .trailing
      static let sideRegionAlignment: Alignment = .center
      static let timerAlignment: Alignment = .trailing
      static let timerRegionPriority: Double = 1
      static let titleFontSize: CGFloat = 16
      static let titleMinimumScaleFactor: CGFloat = 0.75
      static let timerFontSize: CGFloat = 26
      static let timerLineHeight: CGFloat = 31
      static let buttonWidth: CGFloat = 60
      static let buttonHeight: CGFloat = 26
      static let buttonFontSize: CGFloat = 12
    }
  }

  enum Heatmap {
    static let weekdayLabels = ["일", "월", "화", "수", "목", "금", "토"]
    static let bucketThresholdSeconds = [1800, 3600, 5400]
    static let bucketAccentWeights = [0.24, 0.48, 0.74, 1]
    static let weekdayLabelHeightInCells: CGFloat = 1
    static let weekendWeekdayLabels = ["일", "토"]
    static let weekdayLabelSize: CGFloat = 8
    static let emptyCellLabelColorRole: LoofitHeatmapCellLabelColorRole = .textLow
    static let filledCellLabelColorRole: LoofitHeatmapCellLabelColorRole = .textHigh
    static let strongFilledCellLabelColorRole: LoofitHeatmapCellLabelColorRole = .onAccent
    static let strongCellLabelMinimumDurationSeconds = 3600
    static let week = LoofitHeatmapRendererSpec(
      title: "지난 7일",
      rangeDays: 7,
      rangeWeeks: 0,
      rangeMonths: 0,
      columns: 7,
      contentPadding: 12,
      cellGap: 4,
      cellRadius: 3,
      cellLabelSize: 8,
      cellLabelMinimumScaleFactor: 0.6,
      headerGap: 8,
      headerVisible: false,
      headerFontSize: 12,
      headerLineHeight: 16,
      headerMinimumScaleFactor: 0.75,
      headerSummary: .none,
      calendarAlignment: .rollingDays,
      showLeadingCalendarCells: false,
      monthBoundaryGapSlots: 0,
      reservedHeaderHeight: 0,
      reservedFooterHeight: 63
    )
    static let month = LoofitHeatmapRendererSpec(
      title: "지난 5주",
      rangeDays: 0,
      rangeWeeks: 5,
      rangeMonths: 0,
      columns: 7,
      contentPadding: 12,
      cellGap: 4,
      cellRadius: 3,
      cellLabelSize: 8,
      cellLabelMinimumScaleFactor: 0.6,
      headerGap: 8,
      headerVisible: false,
      headerFontSize: 12,
      headerLineHeight: 16,
      headerMinimumScaleFactor: 0.75,
      headerSummary: .none,
      calendarAlignment: .calendarWeeks,
      showLeadingCalendarCells: false,
      monthBoundaryGapSlots: 0,
      reservedHeaderHeight: 0,
      reservedFooterHeight: 18
    )
    static let year = LoofitHeatmapRendererSpec(
      title: "지난 6개월",
      rangeDays: 0,
      rangeWeeks: 0,
      rangeMonths: 6,
      columns: 0,
      contentPadding: 12,
      cellGap: 2,
      cellRadius: 3,
      cellLabelSize: 0,
      cellLabelMinimumScaleFactor: 0.6,
      headerGap: 8,
      headerVisible: true,
      headerFontSize: 8,
      headerLineHeight: 10,
      headerMinimumScaleFactor: 0.75,
      headerSummary: .countTotalAverage,
      calendarAlignment: .continuousMonthsWithBoundarySlots,
      showLeadingCalendarCells: true,
      monthBoundaryGapSlots: 7,
      reservedHeaderHeight: 22,
      reservedFooterHeight: 0
    )

    static let monthLabelSize: CGFloat = 8
    static let monthLabelHeight: CGFloat = 16
    static let monthHeaderBottomGap: CGFloat = 8

    enum WeekFooter {
      static let statOrder: [LoofitHeatmapStat] = [.count, .totalDuration, .averageDuration]
      static let statLabels = ["횟수", "총 시간", "평균"]
      static let recentLabel = "최근 운동"
      static let emptyRecentLabel = "아직 기록 없음"
      static let alwaysShowRecent = true
      static let recentLimit = 2
      static let topRowGap: CGFloat = 8
      static let statGap: CGFloat = 4
      static let recentRowGap: CGFloat = 2
      static let statLabelSize: CGFloat = 8
      static let statValueSize: CGFloat = 16
      static let statValueMinimumScale: CGFloat = 0.75
      static let recentLabelSize: CGFloat = 8
      static let recentValueSize: CGFloat = 12
      static let recentMetaSize: CGFloat = 8
    }

    enum MonthFooter {
      static let statOrder: [LoofitHeatmapStat] = [.count, .totalDuration]
      static let separator = " · "
      static let totalDurationPrefix = "총 "
    }
  }

  enum LockScreen {
    static let active = "운동 중"
    static let completedEyebrow = "오늘 완료"
    static let completedBadge = "오운완"
    static let idle = "다음 운동"
    static let routineRequired = "루틴 설정 필요"
    static let compactCharacterLimit = 3
    static let inlineFontSize: CGFloat = 12
    static let inlineMinimumScaleFactor: CGFloat = 0.75
    static let circularDefaultFontSize: CGFloat = 16
    static let circularCompletedFontSize: CGFloat = 16
    static let circularMinimumScaleFactor: CGFloat = 0.48
    static let circularHorizontalPadding: CGFloat = 2
    static let rectangularTitleFontSize: CGFloat = 26
    static let rectangularTitleMinimumScaleFactor: CGFloat = 0.62
    static let rectangularDetailFontSize: CGFloat = 16
    static let rectangularDetailMinimumScaleFactor: CGFloat = 0.68

    enum ThreeWeekCalendar {
      static let rangeWeeks = 3
      static let columns = 7
      static let contentPadding: CGFloat = 2
      static let cellGap: CGFloat = 2
      static let cellRadius: CGFloat = 3
      static let cellLabelSize: CGFloat = 8
      static let cellLabelMinimumScaleFactor: CGFloat = 0.68
      static let weekdayLabelSize: CGFloat = 8
      static let weekdayLabelLineHeight: CGFloat = 10
      static let dimmedWeekdayLabels = ["일", "토"]
      static let dimmedWeekdayOpacity: Double = 0.72
      static let bucketOpacities: [Double] = [0.28, 0.48, 0.72, 1]
      static let todayIndicatorColor = "#FFFFFF"
      static let todayIndicatorWidth: CGFloat = 1
    }
  }
}
