fastlane_directory = File.expand_path("fastlane", Dir.pwd)

metadata_path(File.join(fastlane_directory, "metadata"))
screenshots_path(File.join(fastlane_directory, "screenshots"))
app_previews_path(File.join(fastlane_directory, "app-previews"))

skip_binary_upload(true)
submit_for_review(false)
force(false)
overwrite_screenshots(true)
precheck_include_in_app_purchases(false)
