// Generated by scripts/generate-widget-renderer-contract.mjs. Do not edit.
// Edit src/widgets/widget-renderer-contract.json and regenerate instead.

public enum LoofitWidgetLayoutContract {
  public static let fingerprint = "b0721ee28787205cb8a0ba6aeef2bfd47ab565fb16093822faab27eb138e96f4"
  public static let calendarRows = 7

  public enum SurfaceKinds {
    public static let control = "WorkoutControlWidget"
    public static let heatmapWeek = "HeatmapWeekWidget"
    public static let heatmapMonth = "HeatmapMonthWidget"
    public static let heatmapSixMonths = "HeatmapYearWidget"
    public static let currentMonth = "CurrentMonthCalendarWidget"
    public static let fourWeekExpanded = "HeatmapFourWeekExpandedWidget"
    public static let routineProgress = "RoutineProgressWidget"
    public static let bodyPartDuration = "BodyPartDurationWidget"
    public static let lockWorkout = "WorkoutLockScreenWidget"
    public static let lockThreeWeek = "ThreeWeekCalendarLockScreenWidget"
    public static let lockNextThreeWeek = "NextThreeWeekCalendarLockScreenWidget"
    public static let lockRoutineProgress = "RoutineProgressLockScreenWidget"
    public static let all = [
      control,
      heatmapWeek,
      heatmapMonth,
      heatmapSixMonths,
      currentMonth,
      fourWeekExpanded,
      routineProgress,
      bodyPartDuration,
      lockWorkout,
      lockThreeWeek,
      lockNextThreeWeek,
      lockRoutineProgress,
    ]
  }

  public enum HeaderSummary: String, Sendable {
    case none
    case count
    case countTotalAverage
  }

  public enum CalendarAlignment: String, Sendable {
    case rollingDays
    case calendarWeeks
    case continuousMonthsWithBoundarySlots
  }

  public enum HeatmapStat: String, Sendable {
    case count
    case totalDuration
    case averageDuration
  }

  public enum Heatmap {
    public static let weekRangeDays = 7
    public static let monthRangeWeeks = 5
    public static let sixMonthRangeMonths = 6
    public static let monthBoundaryGapSlots = 7
    public static let currentMonthMaxRows = 6
    public static let fourWeekExpandedRangeWeeks = 4
    public static let weekHeaderSummary: HeaderSummary = .none
    public static let monthHeaderSummary: HeaderSummary = .none
    public static let sixMonthHeaderSummary: HeaderSummary = .countTotalAverage
    public static let weekCalendarAlignment: CalendarAlignment = .rollingDays
    public static let monthCalendarAlignment: CalendarAlignment = .calendarWeeks
    public static let sixMonthCalendarAlignment: CalendarAlignment = .continuousMonthsWithBoundarySlots
    public static let weekStatOrder: [HeatmapStat] = [.count, .totalDuration, .averageDuration]
    public static let monthStatOrder: [HeatmapStat] = [.count, .totalDuration]
    public static let weekAlwaysShowsRecent = true
  }

  public enum RoutineProgress {
    public static let visibleItemLimit = 4
  }

  public enum BodyPartDuration {
    public static let rangeDays = 30
    public static let visibleItemLimit = 4
  }

  public enum LockScreen {
    public static let threeWeekCalendarRangeWeeks = 3
    public static let nextThreeWeekCalendarRangeWeeks = 3
  }
}
