// Generated by scripts/generate-workout-schema.mjs from contracts/workout-schema.json.
// Do not edit this file directly.

import Foundation

struct LoofitWorkoutSchemaColumnMigration {
  let table: String
  let column: String
  let definition: String
}

struct LoofitWorkoutSchemaMigrationStep {
  let id: String
  let version: Int
  let schemaSQL: String
  let columns: [LoofitWorkoutSchemaColumnMigration]
  let postSchemaSQL: String
  let afterSQL: String?
}

enum LoofitWorkoutSchemaContract {
  static let databaseName = "loofit.db"
  static let currentVersion = 3
  static let migrations: [LoofitWorkoutSchemaMigrationStep] = [
    LoofitWorkoutSchemaMigrationStep(
      id: "initial_schema",
      version: 1,
      schemaSQL: """
CREATE TABLE IF NOT EXISTS body_parts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  is_archived INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS routines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS routine_days (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  routine_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS routine_day_parts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  routine_day_id INTEGER NOT NULL,
  body_part_id INTEGER NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS workout_sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  routine_id INTEGER,
  routine_day_id INTEGER,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (status IN ('active', 'completed', 'canceled')),
  note TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workout_session_parts_snapshot (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workout_session_id INTEGER NOT NULL,
  body_part_id INTEGER,
  body_part_name TEXT NOT NULL,
  body_part_color TEXT NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS routine_progress (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  active_routine_id INTEGER,
  next_routine_day_id INTEGER,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY NOT NULL,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

""",
      columns: [],
      postSchemaSQL: """
CREATE INDEX IF NOT EXISTS idx_sessions_status_started_at
  ON workout_sessions(status, started_at);

CREATE INDEX IF NOT EXISTS idx_session_parts_session_id
  ON workout_session_parts_snapshot(workout_session_id);

""",
      afterSQL: nil
    ),
    LoofitWorkoutSchemaMigrationStep(
      id: "widget_sync",
      version: 2,
      schemaSQL: """
CREATE TABLE IF NOT EXISTS widget_sync_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  desired_revision INTEGER NOT NULL DEFAULT 1,
  published_revision INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  updated_at TEXT NOT NULL
);

INSERT OR IGNORE INTO widget_sync_state
  (id, desired_revision, published_revision, last_error, updated_at)
VALUES
  (1, 1, 0, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));

""",
      columns: [],
      postSchemaSQL: """
UPDATE workout_sessions
SET status = 'canceled',
    ended_at = COALESCE(ended_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    duration_seconds = CAST(MAX(
      0,
      (julianday('now') - COALESCE(julianday(started_at), julianday('now'))) * 86400
    ) AS INTEGER),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE status = 'active'
  AND id NOT IN (
    SELECT id
    FROM workout_sessions
    WHERE status = 'active'
    ORDER BY started_at DESC, id DESC
    LIMIT 1
  );

CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_single_active
  ON workout_sessions(status)
  WHERE status = 'active';

DROP TRIGGER IF EXISTS widget_sync_body_parts_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_insert
AFTER INSERT ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_body_parts_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_update
AFTER UPDATE ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_body_parts_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_delete
AFTER DELETE ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routines_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_insert
AFTER INSERT ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routines_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_update
AFTER UPDATE ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routines_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_delete
AFTER DELETE ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_days_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_insert
AFTER INSERT ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_days_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_update
AFTER UPDATE ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_days_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_delete
AFTER DELETE ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_day_parts_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_insert
AFTER INSERT ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_day_parts_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_update
AFTER UPDATE ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_day_parts_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_delete
AFTER DELETE ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_sessions_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_insert
AFTER INSERT ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_sessions_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_update
AFTER UPDATE ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_sessions_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_delete
AFTER DELETE ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_session_parts_snapshot_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_insert
AFTER INSERT ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_session_parts_snapshot_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_update
AFTER UPDATE ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_session_parts_snapshot_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_delete
AFTER DELETE ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_progress_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_insert
AFTER INSERT ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_progress_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_update
AFTER UPDATE ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_progress_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_delete
AFTER DELETE ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_app_settings_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_insert
AFTER INSERT ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_app_settings_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_update
AFTER UPDATE ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_app_settings_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_delete
AFTER DELETE ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;

""",
      afterSQL: nil
    ),
    LoofitWorkoutSchemaMigrationStep(
      id: "routine_day_name_snapshot",
      version: 3,
      schemaSQL: """
INSERT OR IGNORE INTO widget_sync_state
  (id, desired_revision, published_revision, last_error, updated_at)
VALUES
  (1, 1, 0, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));

""",
      columns: [
        LoofitWorkoutSchemaColumnMigration(table: "workout_sessions", column: "routine_day_name_snapshot", definition: "TEXT"),
      ],
      postSchemaSQL: """
DROP TRIGGER IF EXISTS widget_sync_body_parts_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_insert
AFTER INSERT ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_body_parts_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_update
AFTER UPDATE ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_body_parts_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_delete
AFTER DELETE ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routines_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_insert
AFTER INSERT ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routines_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_update
AFTER UPDATE ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routines_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_delete
AFTER DELETE ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_days_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_insert
AFTER INSERT ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_days_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_update
AFTER UPDATE ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_days_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_delete
AFTER DELETE ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_day_parts_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_insert
AFTER INSERT ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_day_parts_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_update
AFTER UPDATE ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_day_parts_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_delete
AFTER DELETE ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_sessions_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_insert
AFTER INSERT ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_sessions_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_update
AFTER UPDATE ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_sessions_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_delete
AFTER DELETE ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_session_parts_snapshot_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_insert
AFTER INSERT ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_session_parts_snapshot_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_update
AFTER UPDATE ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_workout_session_parts_snapshot_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_delete
AFTER DELETE ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_progress_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_insert
AFTER INSERT ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_progress_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_update
AFTER UPDATE ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_routine_progress_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_delete
AFTER DELETE ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_app_settings_insert;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_insert
AFTER INSERT ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_app_settings_update;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_update
AFTER UPDATE ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
DROP TRIGGER IF EXISTS widget_sync_app_settings_delete;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_delete
AFTER DELETE ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;

""",
      afterSQL: """
UPDATE workout_sessions
SET routine_day_name_snapshot = COALESCE(
  NULLIF(TRIM((
    SELECT rd.name
    FROM routine_days rd
    WHERE rd.id = workout_sessions.routine_day_id
    LIMIT 1
  )), ''),
  NULLIF((
    SELECT GROUP_CONCAT(ordered_parts.body_part_name, ' · ')
    FROM (
      SELECT sp.body_part_name
      FROM workout_session_parts_snapshot sp
      WHERE sp.workout_session_id = workout_sessions.id
      ORDER BY sp.sort_order ASC, sp.id ASC
    ) AS ordered_parts
  ), ''),
  '삭제된 분할'
)
WHERE routine_day_id IS NOT NULL
  AND routine_day_name_snapshot IS NULL;
"""
    ),
  ]
  static let widgetSyncOperations = ["INSERT", "UPDATE", "DELETE"]
  static let widgetSyncStateTable = "widget_sync_state"
  static let widgetSyncTrackedTables = ["body_parts", "routines", "routine_days", "routine_day_parts", "workout_sessions", "workout_session_parts_snapshot", "routine_progress", "app_settings"]
  static let workoutSessionsTable = "workout_sessions"

  static let widgetSyncStateBootstrapSQL = """
CREATE TABLE IF NOT EXISTS widget_sync_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  desired_revision INTEGER NOT NULL DEFAULT 1,
  published_revision INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  updated_at TEXT NOT NULL
);

INSERT OR IGNORE INTO widget_sync_state
  (id, desired_revision, published_revision, last_error, updated_at)
VALUES
  (1, 1, 0, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));
"""

  static func widgetSyncTriggerSQL(table: String, operation: String) -> String {
    let trigger = "widget_sync_" + table + "_" + operation.lowercased()
    return """
CREATE TRIGGER IF NOT EXISTS \(trigger)
AFTER \(operation) ON \(table)
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
"""
  }

  static let singleActiveSessionInvariantSQL = """
UPDATE workout_sessions
SET status = 'canceled',
    ended_at = COALESCE(ended_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    duration_seconds = CAST(MAX(
      0,
      (julianday('now') - COALESCE(julianday(started_at), julianday('now'))) * 86400
    ) AS INTEGER),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE status = 'active'
  AND id NOT IN (
    SELECT id
    FROM workout_sessions
    WHERE status = 'active'
    ORDER BY started_at DESC, id DESC
    LIMIT 1
  );
CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_single_active
  ON workout_sessions(status)
  WHERE status = 'active';
"""

  static let schemaMigrationFixtureSQL = """
CREATE TABLE IF NOT EXISTS body_parts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  is_archived INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS routines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS routine_days (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  routine_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS routine_day_parts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  routine_day_id INTEGER NOT NULL,
  body_part_id INTEGER NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS workout_sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  routine_id INTEGER,
  routine_day_id INTEGER,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (status IN ('active', 'completed', 'canceled')),
  note TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workout_session_parts_snapshot (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workout_session_id INTEGER NOT NULL,
  body_part_id INTEGER,
  body_part_name TEXT NOT NULL,
  body_part_color TEXT NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS routine_progress (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  active_routine_id INTEGER,
  next_routine_day_id INTEGER,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY NOT NULL,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS widget_sync_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  desired_revision INTEGER NOT NULL DEFAULT 1,
  published_revision INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  updated_at TEXT NOT NULL
);

INSERT OR IGNORE INTO widget_sync_state
  (id, desired_revision, published_revision, last_error, updated_at)
VALUES
  (1, 1, 0, NULL, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'));

CREATE INDEX IF NOT EXISTS idx_sessions_status_started_at
  ON workout_sessions(status, started_at);

CREATE INDEX IF NOT EXISTS idx_session_parts_session_id
  ON workout_session_parts_snapshot(workout_session_id);

UPDATE workout_sessions
SET status = 'canceled',
    ended_at = COALESCE(ended_at, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    duration_seconds = CAST(MAX(
      0,
      (julianday('now') - COALESCE(julianday(started_at), julianday('now'))) * 86400
    ) AS INTEGER),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE status = 'active'
  AND id NOT IN (
    SELECT id
    FROM workout_sessions
    WHERE status = 'active'
    ORDER BY started_at DESC, id DESC
    LIMIT 1
  );

CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_single_active
  ON workout_sessions(status)
  WHERE status = 'active';

CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_insert
AFTER INSERT ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_update
AFTER UPDATE ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_body_parts_delete
AFTER DELETE ON body_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_insert
AFTER INSERT ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_update
AFTER UPDATE ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routines_delete
AFTER DELETE ON routines
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_insert
AFTER INSERT ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_update
AFTER UPDATE ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_days_delete
AFTER DELETE ON routine_days
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_insert
AFTER INSERT ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_update
AFTER UPDATE ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_day_parts_delete
AFTER DELETE ON routine_day_parts
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_insert
AFTER INSERT ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_update
AFTER UPDATE ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_sessions_delete
AFTER DELETE ON workout_sessions
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_insert
AFTER INSERT ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_update
AFTER UPDATE ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_workout_session_parts_snapshot_delete
AFTER DELETE ON workout_session_parts_snapshot
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_insert
AFTER INSERT ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_update
AFTER UPDATE ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_routine_progress_delete
AFTER DELETE ON routine_progress
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_insert
AFTER INSERT ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_update
AFTER UPDATE ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;
CREATE TRIGGER IF NOT EXISTS widget_sync_app_settings_delete
AFTER DELETE ON app_settings
BEGIN
  UPDATE widget_sync_state
  SET desired_revision = desired_revision + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = 1;
END;

PRAGMA user_version = 2;

"""
}
