// Generated by scripts/generate-widget-renderer-contract.mjs. Do not edit.
// Edit src/widgets/widget-renderer-contract.json and regenerate instead.

public enum LoofitWidgetLayoutContract {
  public static let calendarRows = 7

  public enum HeaderSummary: String, Sendable {
    case none
    case count
    case countTotalAverage
  }

  public enum CalendarAlignment: String, Sendable {
    case rollingDays
    case calendarWeeks
    case continuousMonthsWithBoundarySlots
  }

  public enum HeatmapStat: String, Sendable {
    case count
    case totalDuration
    case averageDuration
  }

  public enum Heatmap {
    public static let weekRangeDays = 7
    public static let monthRangeWeeks = 5
    public static let sixMonthRangeMonths = 6
    public static let monthBoundaryGapSlots = 7
    public static let currentMonthMaxRows = 6
    public static let fourWeekExpandedRangeWeeks = 4
    public static let weekHeaderSummary: HeaderSummary = .none
    public static let monthHeaderSummary: HeaderSummary = .none
    public static let sixMonthHeaderSummary: HeaderSummary = .countTotalAverage
    public static let weekCalendarAlignment: CalendarAlignment = .rollingDays
    public static let monthCalendarAlignment: CalendarAlignment = .calendarWeeks
    public static let sixMonthCalendarAlignment: CalendarAlignment = .continuousMonthsWithBoundarySlots
    public static let weekStatOrder: [HeatmapStat] = [.count, .totalDuration, .averageDuration]
    public static let monthStatOrder: [HeatmapStat] = [.count, .totalDuration]
    public static let weekAlwaysShowsRecent = true
  }

  public enum RoutineProgress {
    public static let visibleItemLimit = 3
  }

  public enum BodyPartDuration {
    public static let rangeDays = 30
    public static let visibleItemLimit = 4
  }

  public enum LockScreen {
    public static let threeWeekCalendarRangeWeeks = 3
    public static let nextThreeWeekCalendarRangeWeeks = 3
  }
}
